title: "Notiatanasiano"  # Tu título
url: "https://jusata.github.io"  # Tu URL

institution:
  name: "Institución Educativa Atanasio Girardot"
  location: "Girardota, Antioquia"
  logo: "/assets/images/logo.png"
  anthem: "/assets/audio/himno.mp3"


social:
  facebook: "https://facebook.com/profile.php?id=100008360917770"
  youtube: "https://www.youtube.com/@juliansancheztaborda5203"
  instagram: "https://www.instagram.com/ie.atanasio"