title: "Notiatanasiano"
url: "https://jusata.github.io"
baseurl: "/notiatanasiano"

institution:
  name: "Institución Educativa Atanasio Girardot"
  location: "Girardota, Antioquia"
  logo: "/assets/images/logo.png"
  anthem: "/assets/audio/himno.mp3"

social:
  facebook: "https://facebook.com/profile.php?id=100008360917770"
  youtube: "https://www.youtube.com/@juliansancheztaborda5203"
  instagram: "https://www.instagram.com/ie.atanasio"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  noticias:
    output: true
    permalink: /noticias/:title/
  eventos:
    output: true
    permalink: /eventos/:title/

defaults:
  - scope:
      path: ""
      type: "noticias"
    values:
      layout: "noticia"
  - scope:
      path: ""
      type: "eventos"
    values:
      layout: "evento"

paginate: 9
paginate_path: "/noticias/page:num/"

timezone: America/Bogota

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
EOF
